# Generated by Django 4.0 on 2021-12-26 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zekefashion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(blank=True, max_length=5000, null=True)),
                ('firstline', models.CharField(default='Welcome To', max_length=50)),
                ('secandline', models.CharField(default='Freshshop', max_length=50)),
                ('therdline', models.CharField(default='See how your users experience your website in realtime or view', max_length=200)),
                ('forthline', models.CharField(default='trends to see any changes in performance over time.', max_length=200)),
                ('buttontext', models.CharField(default='Shop New', max_length=50)),
                ('buttonclick', models.URLField(default='#')),
            ],
        ),
    ]
