# Generated by Django 4.0 on 2021-12-31 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zekefashion', '0002_banners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banners',
            name='buttonclick',
            field=models.URLField(default='http://127.0.0.1:8000/'),
        ),
    ]
