# Generated by Django 4.0 on 2021-12-31 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zekefashion', '0003_alter_banners_buttonclick'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home_page_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(blank=True, max_length=5000, null=True)),
                ('categoryname', models.CharField(default='Category Name', max_length=50)),
            ],
        ),
    ]
