# Generated by Django 4.0 on 2021-12-31 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zekefashion', '0004_home_page_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home_page_category',
            old_name='categoryname',
            new_name='CategoryName',
        ),
        migrations.RenameField(
            model_name='home_page_category',
            old_name='image',
            new_name='Image',
        ),
    ]
