# Generated by Django 4.0 on 2021-12-31 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zekefashion', '0005_rename_categoryname_home_page_category_categoryname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='home_page_category',
            name='buttonclick',
            field=models.URLField(default='http://127.0.0.1:8000/'),
        ),
    ]
