# Generated by Django 4.0 on 2021-12-31 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zekefashion', '0006_home_page_category_buttonclick'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='home_page_category',
            table='state',
        ),
    ]
