# Generated by Django 4.0 on 2022-01-09 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zekefashion', '0008_alter_home_page_category_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home_page_offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(blank=True, max_length=5000, null=True)),
                ('onclick', models.URLField(default='http://127.0.0.1:8000/')),
            ],
            options={
                'verbose_name': 'Home page offer',
                'db_table': 'Homepageoffer',
            },
        ),
        migrations.AlterModelOptions(
            name='home_page_category',
            options={'verbose_name': 'Category'},
        ),
    ]
