# Generated by Django 4.0 on 2022-01-09 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zekefashion', '0010_alter_product_options_product_offer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='offer',
            field=models.CharField(max_length=10),
        ),
    ]
